### ISSUE TITLE
DFM2PM Converter is in the wrong package

### ISSUE THREAD

**Issue by s-j-v-zelst** [pm4knime/pm4knime-development#14]
The DFM2PM converter (which is a very cryptic name), is not located in the conversion package.
This is weird, as it "converts" a given input into an output.

**Comment by KFDing** [comment]
Hi, 
I also felt a bit confusing when creating the package for it. Although the node looks like just converting one input to another. But in background, the discovery process is conducted. That's why I didn't put it in the conversion category.  
I think, I will change the name  "DFM2PM Converter" to "DFM2PN Miner".
Regards
Kefang
