### ISSUE TITLE
Exported XLog misses something from the original log

### ISSUE THREAD

**Issue by fit-alessandro-berti** [pm4knime/pm4knime-development#7]
This probably depends on the export plugin. First a picture of the original log with the extensions, after a picture of the exported log:
![image](https://user-images.githubusercontent.com/56342194/69606672-b3859f80-1023-11ea-99a4-2dc6d4c2ed19.png)
![image](https://user-images.githubusercontent.com/56342194/69606676-b8e2ea00-1023-11ea-851e-5705c4e7d731.png)

**Comment by KFDing** [comment]
Hi @fit-alessandro-berti , could you send me the event log??So I can check the problem easier? Thanks!

**Comment by KFDing** [comment]
Hi @fit-alessandro-berti , 
I have checked the data and found the reason is caused by the un-recognization of extensions during the parsing phase. The extension like "MetaData_Time". Because I have no control of parsing part, so I can't solve it directly, but will propose the responsible people about this issue. 

Regards Kefang

**Comment by KFDing** [comment]
Hi, @fit-alessandro-berti ,
I have added a new option to allow reading all extensions from the xml. The method is called "IEEE Lenient".  
Regards Kefang
